In [1]:
import torch
import numpy as np
import time
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size=8
batch_size=4

cuda


In [2]:
start=time.time()
zeros=torch.zeros(1,1)
end=time.time()

elapsed=end-start
print(f"{elapsed:.4f}")

0.0040


In [16]:
with open('wiz_of_oz.txt','r',encoding='utf-8') as f:
    text=f.read()

chars=sorted(set(text))
print(chars)
vocab_size=len(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [4]:
string_to_int={ch:i for i,ch in enumerate(chars)}
int_to_string={i:ch for i,ch in enumerate(chars)}
encode=lambda s:[string_to_int[c] for c in s]
decode=lambda l:''.join([int_to_string[i] for i in l])

data= torch.tensor(encode(text),dtype=torch.long)
print(data[:100])

tensor([75, 27, 63, 66, 63, 68, 56, 73,  1, 49, 62, 52,  1, 68, 56, 53,  1, 46,
        57, 74, 49, 66, 52,  1, 57, 62,  1, 38, 74,  0,  0,  0,  1,  1, 24,  1,
        29, 49, 57, 68, 56, 54, 69, 60,  1, 41, 53, 51, 63, 66, 52,  1, 63, 54,
         1, 43, 56, 53, 57, 66,  1, 24, 61, 49, 74, 57, 62, 55,  1, 24, 52, 70,
        53, 62, 68, 69, 66, 53, 67,  0,  1,  1,  1,  1, 57, 62,  1, 49, 62,  1,
        44, 62, 52, 53, 66, 55, 66, 63, 69, 62])


In [20]:
n=int(0.8*len(data))
train_data=data[:n]
val_data=data[n:]

def get_batch(split):
    data=train_data if split=="train" else val_data
    ix=torch.randint(len(data)-block_size, (batch_size,))
    print(ix)
    x=torch.stack([data[i:i+block_size]for i in ix ])
    y=torch.stack([data[i+1:i+block_size+1]for i in ix ])
    return x,y
x,y=get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)

tensor([146755,  63091,  93508, 105981])
inputs:
tensor([[52, 55, 53,  1, 63, 54,  1, 68],
        [ 1, 49, 62, 52,  1, 71, 53, 62],
        [ 1, 71, 53,  1, 52, 63, 22,  1],
        [61,  1, 49, 60, 60, 10,  0,  0]])
targets:
tensor([[55, 53,  1, 63, 54,  1, 68, 56],
        [49, 62, 52,  1, 71, 53, 62, 68],
        [71, 53,  1, 52, 63, 22,  1, 73],
        [ 1, 49, 60, 60, 10,  0,  0,  0]])


In [19]:

x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
    context=x[:t+1]
    target=y[t]
    print("when input is",context,"output is",target)

when input is tensor([75]) output is tensor(27)
when input is tensor([75, 27]) output is tensor(63)
when input is tensor([75, 27, 63]) output is tensor(66)
when input is tensor([75, 27, 63, 66]) output is tensor(63)
when input is tensor([75, 27, 63, 66, 63]) output is tensor(68)
when input is tensor([75, 27, 63, 66, 63, 68]) output is tensor(56)
when input is tensor([75, 27, 63, 66, 63, 68, 56]) output is tensor(73)
when input is tensor([75, 27, 63, 66, 63, 68, 56, 73]) output is tensor(1)


In [ ]:
'''rand=torch.randint(-100,100,(6,))
print(rand)'''

tensor([ 31, -85, -48,  90, -48,  36])


In [ ]:
'''tensor=torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor'''

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [ ]:
'''zeros=torch.zeros(2,3)
zeros'''

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
'''input=torch.empty(2,3)
input'''

tensor([[-1.5870e-02,  1.8077e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
'''arrange=torch.arange(5)
arrange'''

tensor([0, 1, 2, 3, 4])

In [ ]:
'''torch_r1=torch.rand(100,100,100,100).to(device)
torch_r2=torch.rand(100,100,100,100).to(device)
np_r1=torch.rand(100,100,100,100)
np_r2=torch.rand(100,100,100,100)

start=time.time()
rand=(torch_r1 @ torch_r2)
end=time.time()

elap=end-start
print(f"{elap:.8f}")

start=time.time()
rand=np.multiply(np_r1,np_r2)
end=time.time()

elap=end-start
print(f"{elap:.8f}")'''

0.18363166
0.13734961


In [ ]:
'''import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False)
print(linear(sample))'''

tensor([3.7664, 0.8047, 4.7758], grad_fn=<SqueezeBackward4>)


In [ ]:
'''import torch.nn.functional as f

tensor1=torch.tensor([1.0,2.0,3.0])

softmax_op=f.softmax(tensor1,dim=0)

print(softmax_op)'''

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
'''vocab_size=80
embedding_dim=6
embedding=nn.Embedding(vocab_size,embedding_dim)

ip_indices=torch.LongTensor([1,5,3,2])

eb_op=embedding(ip_indices)

print(eb_op.shape)
print(eb_op)'''

torch.Size([4, 6])
tensor([[-0.8019,  0.0300, -2.0528, -0.1077, -0.2335,  0.2438],
        [ 0.8781, -0.4543,  0.4655, -0.2003, -1.7381,  0.4319],
        [-0.5354,  0.4364,  0.3836,  1.2006,  0.0204, -0.1417],
        [-1.5653, -0.7696,  0.1794, -2.3546,  0.9259, -0.1425]],
       grad_fn=<EmbeddingBackward0>)
